### PR TITLE
Add shaped window based on SDL_WINDOW_TRANSPARENT

### PR DESCRIPTION
**Pull request by 1bsyl**
If Shaped Window get removed in SDL3, 
this add back the functionality in SDL2-compat, but only for SDL_Renderer and for 1 window (which could be extended).

### CODE REVIEW

**Comment by 1bsyl** [comment]
(testshape doesn't work perfectly, because there is one bug outside the scope)

**Comment by sezero** [comment]
@1bsyl, @slouken: I rebased this so that it applies cleanly. (Build-tested only, no run-testing!)

Either this, or some new implementation is needed after shaped window removal in SDL3.

**Comment by slouken** [comment]
I have this covered, thanks!

**Comment by sezero** [comment]
>  but only for SDL_Renderer and for 1 window (which could be extended).

Can these limitations be lifted?

> I have this covered, thanks!

Something changed?

**Comment by slouken** [comment]
Yes, the limitations can be lifted. I was working on something that did that, but I ended up deciding it was better to merge than leave it broken for a few days.

**Pull request merged**
