### PR TITLE
Updated for latest SDL changes as of 97d40b9218038edaf7afe61d6114fb48d8f26a82

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by sezero** [comment]
OK.

It seems I failed to notice the return type difference between SDL_setenv_unsafe and SDL_SetEnvironmentVariable: That's one mistake on my part. Although, is it necessary to re-setenv through the unsafe version after SDL_SetEnvironmentVariable?

**Comment by slouken** [comment]
> Although, is it necessary to re-setenv through the unsafe version after SDL_SetEnvironmentVariable?

Yes, in case the application is setting the environment for a new process launch or other libraries using getenv()

**Comment by slouken** [comment]
@madebr, I'm not able to reproduce the Linux build failure on my Linux box. Do you know what's going on here?

**Comment by madebr** [comment]
> @madebr, I'm not able to reproduce the Linux build failure on my Linux box. Do you know what's going on here?

I can't on my (Fedora) Linux system, but I can in a Ubuntu docker container in which I only installed the apt packages: `build-essential cmake ninja-build libx11-devel`.
Then, running `SDL_VIDEO_DRIVER=dummy test/testautomation --filter subsystems` fails with similar output as ci.

**Comment by slouken** [comment]
> > @madebr, I'm not able to reproduce the Linux build failure on my Linux box. Do you know what's going on here?
> 
> I can't reproduce on my (Fedora) Linux system, but I can in a Ubuntu docker container in which I only installed the apt packages: `build-essential cmake ninja-build libx11-devel`. Then, running `SDL_VIDEO_DRIVER=dummy test/testautomation --filter subsystems` fails with similar output as ci.

Great, can you debug and see what's going on?

**Comment by madebr** [comment]
Not a fix, but I can reproduce on my host Fedora linux system now with 
```
SDL_AUDIO_DRIVER=file test/testautomation --filter subsystems_dependRefCountWithExtraInit
```

**Comment by slouken** [comment]
Ah, so can I. Investigating...

**Comment by slouken** [comment]
Okay, so there were 2 bugs, one fixed by https://github.com/libsdl-org/SDL/commit/5b5b1a892672a29aeab08ebee175b992d6832395 and the other fixed by https://github.com/libsdl-org/sdl2-compat/commit/6981f82329870e15833045e0bb8b607408290aae

**Pull request merged**
