### PR TITLE
Updated for the removal of SDL_SCALEMODE_BEST

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by sezero** [comment]
What happens if an sdl2 program sets SDL_SCALEMODE_BEST ?

**Comment by slouken** [comment]
I believe they can only do it via the hint, and best has been defined as linear forever. Did I miss something?

**Comment by sezero** [comment]
Um, I actually meant what happens if an sdl2 program uses `SDL_ScaleModeBest` as its `SDL_ScaleMode` parameter in calls such as `SDL_SetTextureScaleMode`

I myself very well may be confused and/or missing something though.

**Comment by slouken** [comment]
Oh, good point. I'll fix that, and add parameter validation in SDL3.

**Comment by sezero** [comment]
OK

**Pull request merged**
