### PR TITLE
Implement SDL_GetWindowWMInfo

### LINKED ISSUE #2: SDL_syswm.h changes
SDL_SYSWM_TYPE has been renumbered.
SDL_SysWMmsg and SDL_SysWMinfo structure layout has changed

### PR DESCRIPTION
**Pull request by Kontrabant**
Closes #2

### CODE REVIEW

**Comment by sezero** [comment]
`version2` is only needed in wayland case which, if not enabled, leads to warnings.
Suggest the following (on top of your patch) to avoid unused warnings.
```diff
diff --git a/src/sdl2_compat.c b/src/sdl2_compat.c
index e5731c2..b8559ce 100644
--- a/src/sdl2_compat.c
+++ b/src/sdl2_compat.c
@@ -2291,9 +2291,6 @@ SDL_GetTicks64(void)
 static SDL_bool
 SysWMInfo3to2(SDL_SysWMinfo *wminfo3, SDL2_SysWMinfo *wminfo2)
 {
-    Uint32 version2 = SDL_VERSIONNUM((Uint32)wminfo2->version.major,
-                                     (Uint32)wminfo2->version.minor,
-                                     (Uint32)wminfo2->version.patch);
     switch (wminfo3->subsystem) {
 #if defined(SDL_ENABLE_SYSWM_ANDROID)
     case SDL_SYSWM_ANDROID:
@@ -2344,7 +2341,7 @@ SysWMInfo3to2(SDL_SysWMinfo *wminfo3, SDL2_SysWMinfo *wminfo2)
         break;
 #endif
 #if defined(SDL_ENABLE_SYSWM_WAYLAND)
-    case SDL_SYSWM_WAYLAND:
+    case SDL_SYSWM_WAYLAND: {
         /* Before 2.0.6, it was possible to build an SDL with Wayland support
          * (SDL_SysWMinfo will be large enough to hold Wayland info), but build
          * your app against SDL headers that didn't have Wayland support
@@ -2356,6 +2353,9 @@ SysWMInfo3to2(SDL_SysWMinfo *wminfo3, SDL2_SysWMinfo *wminfo2)
          * will need to be recompiled against newer headers or not use Wayland,
          * maybe by forcing SDL_VIDEODRIVER=x11.
          */
+        const Uint32 version2 = SDL_VERSIONNUM((Uint32)wminfo2->version.major,
+                                               (Uint32)wminfo2->version.minor,
+                                               (Uint32)wminfo2->version.patch);
         if (version2 < SDL_VERSIONNUM(2, 0, 6)) {
             wminfo2->subsystem = SDL2_SYSWM_UNKNOWN;
             SDL_SetError("Version must be 2.0.6 or newer");
@@ -2378,7 +2378,7 @@ SysWMInfo3to2(SDL_SysWMinfo *wminfo3, SDL2_SysWMinfo *wminfo2)
                 }
             }
         }
-        break;
+    }   break;
 #endif
 #if defined(SDL_ENABLE_SYSWM_WINDOWS)
     case SDL_SYSWM_WINDOWS:
```

**Comment by Kontrabant** [comment]
> `version2` is only needed in wayland case which, if not enabled, leads to warnings. Suggest the following (on top of your patch) to avoid unused warnings.

Fixed.

**Comment by sezero** [comment]
@icculus: this is good?

**Comment by slouken** [comment]
This looks good to me.

**Pull request merged**
