### PR TITLE
Updated for the latest SDL3 changes

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by sezero** [comment]
TouchID and FingerID semantics changed with SDL3 commit a31dc6dfcb8b3a50a9713702271aeaa7c5930131:
That should be taken care of. The code as is right now is wrong:
```
sdl2_compat.c(2849): Warning! W124: Comparison result always 0
sdl2_compat.c(3003): Warning! W124: Comparison result always 1
sdl2_compat.c(3032): Warning! W124: Comparison result always 1
```

**Comment by sezero** [comment]
Small update to sdl3_include_wrapper.h: [patch.txt](https://github.com/libsdl-org/sdl2-compat/files/14002745/patch.txt)
Inlined below:
```diff
diff --git a/src/sdl3_include_wrapper.h b/src/sdl3_include_wrapper.h
index eff3c15..c37633b 100644
--- a/src/sdl3_include_wrapper.h
+++ b/src/sdl3_include_wrapper.h
@@ -28,6 +28,12 @@
 #ifndef INCL_SDL3_INCLUDE_WRAPPER_H
 #define INCL_SDL3_INCLUDE_WRAPPER_H
 
+#define SDL_SLOW_MEMCPY
+#define SDL_SLOW_MEMMOVE
+#define SDL_SLOW_MEMSET
+
+#define SDL_ThreadID SDL3_ThreadID /* avoid clash with SDL_ThreadID() of SDL2 */
+
 #define SDL_AddEventWatch IGNORE_THIS_VERSION_OF_SDL_AddEventWatch
 #define SDL_AddGamepadMapping IGNORE_THIS_VERSION_OF_SDL_AddGamepadMapping
 #define SDL_AddGamepadMappingsFromRW IGNORE_THIS_VERSION_OF_SDL_AddGamepadMappingsFromRW
@@ -382,8 +388,6 @@
 #define SDL_DestroyHapticEffect IGNORE_THIS_VERSION_OF_SDL_DestroyHapticEffect
 #define SDL_HapticEffectSupported IGNORE_THIS_VERSION_OF_SDL_HapticEffectSupported
 #define SDL_GetHapticEffectStatus IGNORE_THIS_VERSION_OF_SDL_GetHapticEffectStatus
-#define SDL_HapticIndex IGNORE_THIS_VERSION_OF_SDL_HapticIndex
-#define SDL_HapticName IGNORE_THIS_VERSION_OF_SDL_HapticName
 #define SDL_CreateHapticEffect IGNORE_THIS_VERSION_OF_SDL_CreateHapticEffect
 #define SDL_GetNumHapticAxes IGNORE_THIS_VERSION_OF_SDL_GetNumHapticAxes
 #define SDL_GetMaxHapticEffects IGNORE_THIS_VERSION_OF_SDL_GetMaxHapticEffects
@@ -391,7 +395,6 @@
 #define SDL_OpenHaptic IGNORE_THIS_VERSION_OF_SDL_OpenHaptic
 #define SDL_OpenHapticFromJoystick IGNORE_THIS_VERSION_OF_SDL_OpenHapticFromJoystick
 #define SDL_OpenHapticFromMouse IGNORE_THIS_VERSION_OF_SDL_OpenHapticFromMouse
-#define SDL_HapticOpened IGNORE_THIS_VERSION_OF_SDL_HapticOpened
 #define SDL_PauseHaptic IGNORE_THIS_VERSION_OF_SDL_PauseHaptic
 #define SDL_GetHapticFeatures IGNORE_THIS_VERSION_OF_SDL_GetHapticFeatures
 #define SDL_InitHapticRumble IGNORE_THIS_VERSION_OF_SDL_InitHapticRumble
@@ -484,7 +487,6 @@
 #define SDL_Metal_GetLayer IGNORE_THIS_VERSION_OF_SDL_Metal_GetLayer
 #define SDL_MinimizeWindow IGNORE_THIS_VERSION_OF_SDL_MinimizeWindow
 #define SDL_IsMouseHaptic IGNORE_THIS_VERSION_OF_SDL_IsMouseHaptic
-#define SDL_NumHaptics IGNORE_THIS_VERSION_OF_SDL_NumHaptics
 #define SDL_OnApplicationDidBecomeActive IGNORE_THIS_VERSION_OF_SDL_OnApplicationDidBecomeActive
 #define SDL_OnApplicationDidChangeStatusBarOrientation IGNORE_THIS_VERSION_OF_SDL_OnApplicationDidChangeStatusBarOrientation
 #define SDL_OnApplicationDidEnterBackground IGNORE_THIS_VERSION_OF_SDL_OnApplicationDidEnterBackground
@@ -993,7 +995,7 @@
 #define SDL_GetHapticInstanceID IGNORE_THIS_VERSION_OF_SDL_GetHapticInstanceID
 #define SDL_GetHapticName IGNORE_THIS_VERSION_OF_SDL_GetHapticName
 #define SDL_ReadSurfacePixel IGNORE_THIS_VERSION_OF_SDL_ReadSurfacePixel
-#define SDL_ThreadID IGNORE_THIS_VERSION_OF_SDL_ThreadID
+#define SDL_FlipSurface IGNORE_THIS_VERSION_OF_SDL_FlipSurface
 
 
 #define SDL_FUNCTION_POINTER_IS_VOID_POINTER 1
@@ -2438,14 +2440,6 @@
 #undef SDL_GetHapticEffectStatus
 #endif
 
-#ifdef SDL_HapticIndex
-#undef SDL_HapticIndex
-#endif
-
-#ifdef SDL_HapticName
-#undef SDL_HapticName
-#endif
-
 #ifdef SDL_CreateHapticEffect
 #undef SDL_CreateHapticEffect
 #endif
@@ -2474,10 +2468,6 @@
 #undef SDL_OpenHapticFromMouse
 #endif
 
-#ifdef SDL_HapticOpened
-#undef SDL_HapticOpened
-#endif
-
 #ifdef SDL_PauseHaptic
 #undef SDL_PauseHaptic
 #endif
@@ -2846,10 +2836,6 @@
 #undef SDL_IsMouseHaptic
 #endif
 
-#ifdef SDL_NumHaptics
-#undef SDL_NumHaptics
-#endif
-
 #ifdef SDL_OnApplicationDidBecomeActive
 #undef SDL_OnApplicationDidBecomeActive
 #endif
@@ -4882,10 +4868,12 @@
 #undef SDL_ReadSurfacePixel
 #endif
 
-#ifdef SDL_ThreadID
-#undef SDL_ThreadID
+#ifdef SDL_FlipSurface
+#undef SDL_FlipSurface
 #endif
 
+#undef SDL_ThreadID /* see at top. */
+
 /* undefine these macros, too: redefine as SDL3_xxx, if needed. */
 
 #ifdef SDL_enabled_assert
```

**Comment by slouken** [comment]
Okay, all the changes are made and checks have passed. Good to go?

**Comment by sezero** [comment]
> Okay, all the changes are made and checks have passed. Good to go?

Looks like it at first _very quick_ browse.

Is `SDL_TouchID and SDL_FingerID to be Uint64 with 0 being an invalid value`
properly handled?

**Comment by sezero** [comment]
Here is a patch that syncs latest SDL2 with sdl2-compat: [patch2.txt](https://github.com/libsdl-org/sdl2-compat/files/14002809/patch2.txt)

I can apply it after this, too, if you so prefer.

**Comment by slouken** [comment]
> > Okay, all the changes are made and checks have passed. Good to go?
> 
> Looks like it at first _very quick_ browse.
> 
> Is `SDL_TouchID and SDL_FingerID to be Uint64 with 0 being an invalid value` properly handled?

Yes, those IDs come from the API, not from the application, so aside from the cases you pointed out I think we're good to go.

**Comment by slouken** [comment]
> Here is a patch that syncs latest SDL2 with sdl2-compat: [patch2.txt](https://github.com/libsdl-org/sdl2-compat/files/14002809/patch2.txt)
> 
> I can apply it after this, too, if you so prefer.

Sure, go for it.

**Pull request merged**
