### PR TITLE
Deal with mouse coords becoming floats in SDL3.

### PR DESCRIPTION
**Pull request by sezero**
With this, quakespasm seems to run stable with mouse motions, wheel and
buttons. Note the added FIXME in `SDL_MOUSEWHEEL` cases: Any correction
or changes?

Please review.

### CODE REVIEW

**Comment by sezero** [comment]
@1bsyl: I guess this would be the cure for https://github.com/libsdl-org/sdl2-compat/issues/17

**Comment by 1bsyl** [comment]
maybe, does ./testgeometry compile ? if you run it ?

**Comment by 1bsyl** [comment]
(just need to enable BUILD_TEST in cmake)

**Comment by 1bsyl** [comment]
SDL2COMPAT_TESTS:BOOL=ON

**Comment by icculus** [comment]
My plan was to change the SDL_MOUSEMOTION, etc events to different numbers in SDL3, so they don't overlap with SDL2, and generate new events in EventFilter3to2, but now I can't remember why I thought that was necessary, and this is probably the better way to do this if it _isn't_ necessary

**Comment by sezero** [comment]
> maybe, does ./testgeometry compile ? if you run it ?

No

**Comment by 1bsyl** [comment]
indeed fixed!

**Comment by slouken** [comment]
There was some accumulation of mouse deltas that was being done that will need to be replicated in sdl2-compat.

**Comment by icculus** [comment]
I don't know what this is specifically either. :)

**Comment by sezero** [comment]
> It's the code relating to GetScaledMouseDelta() in https://github.com/libsdl-org/SDL/blob/8c3239dee50f06a959b7e772570c716a757315ca/src/events/SDL_mouse.c

`git blame` shows `GetScaledMouseDelta` received updates during 2.26.0 development
as the latest (apart from SDL3 style changes.) Don't know what to do with this.

**Pull request merged**
