### PR TITLE
Add Joystick / Sensor Locks

### PR DESCRIPTION
**Pull request by 1bsyl**

### CODE REVIEW

**Comment by 1bsyl** [comment]
test

**Comment by sezero** [comment]
Do we actually need this?

**Comment by 1bsyl** [comment]
we need the function sure, because there were in SDL2.
they could be empty maybe but not sure ...
but if an app make a deadlock in sdl2 we should do it we sdl2-compat :)

**Comment by sezero** [comment]
I was leaning on the idea of keeping them empty. @slouken?

**Comment by madebr** [comment]
My 2c is we need these implemented, because SDL2 promises stable results across device connects/disconnects.

> In particular, you are guaranteed that the sensor list won't change, so the API functions that take a sensor index will be valid, and sensor events will not be delivered.

**Pull request merged**
