### PR TITLE
Add SDL_SoftStrech, SDL_SoftStrechLinear

### PR DESCRIPTION
**Pull request by 1bsyl**
SDL3 PR:  https://github.com/libsdl-org/SDL/pull/8670
SDL3 issue: https://github.com/libsdl-org/SDL/issues/8667

### CODE REVIEW

**Comment by sezero** [comment]
The following will be needed for tests to pass after SDL3 side realizes the removal:

```diff
diff --git a/src/sdl3_include_wrapper.h b/src/sdl3_include_wrapper.h
index 8ee12b1..5b1ec4e 100644
--- a/src/sdl3_include_wrapper.h
+++ b/src/sdl3_include_wrapper.h
@@ -983,6 +983,10 @@
 #define SDL_GetGamepadMappings IGNORE_THIS_VERSION_OF_SDL_GetGamepadMappings
 #define SDL_GetTouchDevices IGNORE_THIS_VERSION_OF_SDL_GetTouchDevices
 #define SDL_GetTouchDeviceName IGNORE_THIS_VERSION_OF_SDL_GetTouchDeviceName
+#define SDL_strnstr IGNORE_THIS_VERSION_OF_SDL_strnstr
+#define SDL_wcsnstr IGNORE_THIS_VERSION_OF_SDL_wcsnstr
+#define SDL_BlitSurfaceScaledLinear IGNORE_THIS_VERSION_OF_SDL_BlitSurfaceScaledLinear
+#define SDL_BlitSurfaceUncheckedScaledLinear IGNORE_THIS_VERSION_OF_SDL_BlitSurfaceUncheckedScaledLinear
 
 
 #define SDL_FUNCTION_POINTER_IS_VOID_POINTER 1
@@ -4831,6 +4835,22 @@
 #undef SDL_GetTouchDeviceName
 #endif
 
+#ifdef SDL_strnstr
+#undef SDL_strnstr
+#endif
+
+#ifdef SDL_wcsnstr
+#undef SDL_wcsnstr
+#endif
+
+#ifdef SDL_BlitSurfaceScaledLinear
+#undef SDL_BlitSurfaceScaledLinear
+#endif
+
+#ifdef SDL_BlitSurfaceUncheckedScaledLinear
+#undef SDL_BlitSurfaceUncheckedScaledLinear
+#endif
+
 /* undefine these macros too: */
 /* redefine as SDL3_xxx, if needed. */
 
```

**Comment by 1bsyl** [comment]
Thanks @sezero I've added you're diff!

**Comment by 1bsyl** [comment]
now  this compiles locally, but not on github, not sure if this is ok :/

**Comment by sezero** [comment]
> now this compiles locally, but not on github, not sure if this is ok :/

it's OK. if you really want CI success to show itself, you'll have to re-run the workflows after SDL3 side actually realizes the removal.

**Comment by 1bsyl** [comment]
yes makes sense ! thanks

**Comment by 1bsyl** [comment]
(updating the PR)

**Pull request closed without merging**
