### PR TITLE
ci: enable tests

### PR DESCRIPTION
**Pull request by madebr**

### CODE REVIEW

**Comment by madebr** [comment]
I see __only 2__ (!!!) test issues:
- `testautomation --filter audio_resampleLoss` 
    ```
    ERROR: 07/19/24 19:09:00: Assert 'Expected output length 9600000, got 9600004.': Failed
    ```
    Is the test too strict? Or is this actual audio distortion?
- The tests are timing out on the msys2 runners and nothing is actually run. I will look into this.

**Comment by slouken** [comment]
>   Is the test too strict? Or is this actual audio distortion?

I think this is actual audio distortion, I was waiting for @icculus to look into this.

**Comment by sezero** [comment]
Suggest rebasing and retesting especially after eae0b80c095fd6171e524bcca86c4627f547c6c2 which fixed incompatibility between dynapi and main body .

**Comment by madebr** [comment]
I see a [segfault on macos](https://github.com/libsdl-org/sdl2-compat/actions/runs/10272764912/job/28425709274?pr=97#step:14:5935).
Perhaps it's related to https://github.com/libsdl-org/sdl2-compat/issues/206?

**Comment by slouken** [comment]
> I see a [segfault on macos](https://github.com/libsdl-org/sdl2-compat/actions/runs/10272764912/job/28425709274?pr=97#step:14:5935). Perhaps it's related to #206?

I'm sure it is.

**Comment by madebr** [comment]
There is still some [segfault on macos](https://github.com/libsdl-org/sdl2-compat/actions/runs/10274616878/job/28431730244#step:14:5946)
This is using SDL3 hash [`fe5dcf79be0c00d7220ea0a8fdecf1306d2c90d9`](https://github.com/libsdl-org/sdl2-compat/actions/runs/10274616878/job/28431730244#step:8:16) -> https://github.com/libsdl-org/SDL/commit/fe5dcf79be0c00d7220ea0a8fdecf1306d2c90d9

**Comment by slouken** [comment]
> There is still some [segfault on macos](https://github.com/libsdl-org/sdl2-compat/actions/runs/10274616878/job/28431730244#step:14:5946) This is using SDL3 hash [`fe5dcf79be0c00d7220ea0a8fdecf1306d2c90d9`](https://github.com/libsdl-org/sdl2-compat/actions/runs/10274616878/job/28431730244#step:8:16) -> [libsdl-org/SDL@fe5dcf7](https://github.com/libsdl-org/SDL/commit/fe5dcf79be0c00d7220ea0a8fdecf1306d2c90d9)

Fixed in a81922a. @icculus, can you double check that this matches the original SDL2 behavior on macOS?

**Comment by madebr** [comment]
Woohoo! Awesome job, SDL team !

**Comment by madebr** [comment]
@slouken you might want to disable the "Create a merge commit" option for PRs for this repo, and other satellite repos, as well

**Comment by slouken** [comment]
> @slouken you might want to disable the "Create a merge commit" option for PRs for this repo, and other satellite repos, as well

Done!

**Pull request merged**
